import { SearchSunLongitude } from '../dist/vendor/astronomy.js';
import { writeFileSync } from 'node:fs';
const names=['소한','대한','입춘','우수','경칩','춘분','청명','곡우','입하','소만','망종','하지','소서','대서','입추','처서','백로','추분','한로','상강','입동','소설','대설','동지'];
const rows=[];
for(let year=1969;year<=2051;year++)for(let i=0;i<24;i++){
 const lon=(285+i*15)%360;
 const start=new Date(Date.UTC(year,Math.floor(i/2),i%2?15:1));
 const t=SearchSunLongitude(lon,start,14);
 if(!t)throw Error(`Missing term ${year} ${names[i]}`);
 rows.push({name:names[i],longitude:lon,at:t.date.toISOString(),jie:i%2===0,year});
}
writeFileSync('dist/terms.js','// Generated by Astronomy Engine 2.1.19. Computed ephemeris, not an official KASI table.\nexport const TERMS = '+JSON.stringify(rows)+';\n');
console.log(`${rows.length} terms generated`);
